### ISSUE TITLE
Docker / Installation guide

### ISSUE THREAD

**Issue by benhartwich** [LTopx/Le-AI#10]
Hi,

will there be an installation guide for selfhosting a production environment? Perhaps a dockerized system?

**Comment by Peek-A-Booo** [comment]
Thank you for the reminder. Currently, there is only a simple guide recorded in the readme. I will write a comprehensive deployment document in the next few days and notify you when it's ready. Docker system will be released shortly after.

**Comment by Peek-A-Booo** [comment]
Now support docker deployment
