### ISSUE TITLE
Set custom api_base

### ISSUE THREAD

**Issue by johnd0e** [LTopx/Le-AI#11]
Besides OpenAI there are some other api-compatible providers.
Also, sometimes it can be necessary to use reverse proxy.

It would be good to be able to customize api_base in settings.

**Comment by Peek-A-Booo** [comment]
Support configuring proxy.
Click on "Setting" in the lower left corner of the system, and then go to the first menu "API Key" to configure relevant proxies.
![1](https://i.goethan.cc/file/170212b37e8b61e088e55.png)
![2](https://i.goethan.cc/file/dda11f01319f5307534b3.png)

**Comment by johnd0e** [comment]
Thank you for pointing this out.

The only few things missing:
- Ability to set custom model.
  Either entering it's name manually, or selecting from available via `/v1/models` endpoint.
- Sometimes proxy uses prefix other than `/v1`.

**Comment by Peek-A-Booo** [comment]
> Thank you for pointing this out.
> 
> The only few things missing:
> 
> * Ability to set custom model.
>   Either entering it's name manually, or selecting from available via `/v1/models` endpoint.
> * Sometimes proxy uses prefix other than `/v1`.

You are right. I will fix this.
