### ISSUE TITLE
乱码啊

### ISSUE THREAD

**Issue by Mabisi** [LTopx/Le-AI#8]
![image](https://github.com/LTopx/Le-AI/assets/19968269/d1a2eb27-7225-4ab3-b368-671b5f1f856c)

**Comment by Peek-A-Booo** [comment]
方便告知一下使用的浏览器吗？后续还有遇到乱码的情况吗？还有就是不知道切换为其他模型会有乱码的情况出现吗

**Comment by Mabisi** [comment]
> 方便告知一下使用的浏览器吗？后续还有遇到乱码的情况吗？还有就是不知道切换为其他模型会有乱码的情况出现吗

![image](https://github.com/LTopx/Le-AI/assets/19968269/d4e7c931-e4da-4f33-a4d9-360f99fac33a)
gpt 3.5的模型全都乱码。
chrome edge都试了一样的,用的vercel一键部署

**Comment by Peek-A-Booo** [comment]
已修复，可以更新一下最新代码重新部署试试
